import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { DataProvider } from '@/context/metaData'
import { Providers } from '../components/providers'
import ResizeText from '../components/FontResize'
import { Noto_Sans_Display } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const notoSansDisplay = Noto_Sans_Display({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Monas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${notoSansDisplay.className} ${inter.className}`}>
        <DataProvider>
          <Providers>
            {/* <ResizeText> */}
            <div className='text-lightFont bg-lightBg dark:text-darkFont dark:bg-darkBg select-none'>
              {children}
            </div>
            {/* </ResizeText> */}
          </Providers>
        </DataProvider>
      </body>
    </html>
  )
}
