import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { DataProvider } from '@/context/metaData'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Monas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DataProvider>{children}</DataProvider>
      </body>
    </html>
  )
}
